language: php

sudo: false

php:
  - '5.6'

before_install:
 - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b phalcon-v2.0.7
 - (cd cphalcon/ext; export CFLAGS="-g0 -O0 -std=gnu90"; phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j2 &> /dev/null && make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini &> /dev/null)
 - php --ri phalcon

install:
 - composer install

script:
 - vendor/bin/phpunit

after_success:
 - php vendor/bin/coveralls -v

notifications:
  email:
    - caio.f.r.amd@gmail.com
